
import {
  FaReact,
  FaNodeJs,
  FaDocker,
  FaAws,
  FaAngular,
  FaJava,
  FaLinux,
  FaGitAlt,
  FaServer,
  FaLock,
  FaTerminal,
  FaShieldAlt,
  FaMicrosoft,
  FaCloud,
} from "react-icons/fa";
import {
  SiSpringboot,
  SiNestjs,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiNginx,
  SiJenkins,
  SiJsonwebtokens,
  SiAuth0,
  SiTypescript,
  SiJavascript,
  SiAnsible,
  SiKubernetes,
  SiRedis,
  SiApachekafka,
  SiNextdotjs,
  SiTailwindcss,
  SiGraphql,
  SiRabbitmq,
  SiElasticsearch,
  SiPrometheus,
  SiGrafana,
  SiGithub,
  SiSonarqube,
  SiGithubactions,
  SiGradle,
  SiTerraform,
  SiKeycloak,
  SiOpenid,
  SiApachemaven,
} from "react-icons/si";
import {
  HiCubeTransparent,
  HiCommandLine,
  HiCog6Tooth,
} from "react-icons/hi2";

export const skillIcons = {
  frontend: {
    "React": <FaReact className="text-2xl text-blue-400" />,
    "Angular": <FaAngular className="text-2xl text-red-500" />,
    "Next.js": <SiNextdotjs className="text-2xl text-black dark:text-white" />,
    "Tailwind CSS": <SiTailwindcss className="text-2xl text-blue-400" />,
    "ShadCN UI": <FaTerminal className="text-2xl text-gray-800 dark:text-white" />,
    "TypeScript": <SiTypescript className="text-2xl text-blue-500" />,
    "JavaScript": <SiJavascript className="text-2xl text-yellow-400" />,
  },
  backendApis: {
    "Java": <FaJava className="text-2xl text-red-600" />,
    "Spring Boot": <SiSpringboot className="text-2xl text-green-600" />,
    "SSO": <SiKeycloak className="text-2xl text-blue-600" />,
    "OAuth2": <SiAuth0 className="text-2xl text-blue-600" />,
    "OpenID Connect": <SiOpenid className="text-2xl text-green-600" />,
    "RESTful APIs": <FaServer className="text-2xl text-green-500" />,
    "Microservices Architecture": <HiCubeTransparent className="text-2xl text-purple-600" />,
    "Node.js": <FaNodeJs className="text-2xl text-green-600" />,
    "NestJS": <SiNestjs className="text-2xl text-red-600" />,
    "JWT": <SiJsonwebtokens className="text-2xl text-purple-600" />,
    "GraphQL": <SiGraphql className="text-2xl text-pink-500" />,
  },
  databases: {
    "MySQL": <SiMysql className="text-2xl text-blue-600" />,
    "MongoDB": <SiMongodb className="text-2xl text-green-600" />,
    "PostgreSQL": <SiPostgresql className="text-2xl text-blue-400" />,
    "Redis": <SiRedis className="text-2xl text-red-500" />,
    "Kafka": <SiApachekafka className="text-2xl text-gray-800" />,
    "RabbitMQ": <SiRabbitmq className="text-2xl text-orange-500" />,
    "Elasticsearch": <SiElasticsearch className="text-2xl text-yellow-500" />,
  },
  devOpsCloud: {
    "AWS": <FaAws className="text-2xl text-orange-400" />,
    "Azure": <FaMicrosoft className="text-2xl text-blue-500" />,
    "Alibaba Cloud": <FaCloud className="text-2xl text-orange-600" />,
    "Docker": <FaDocker className="text-2xl text-blue-500" />,
    "Kubernetes": <SiKubernetes className="text-2xl text-blue-500" />,
    "Linux/Unix": <FaLinux className="text-2xl text-black dark:text-white" />,
    "CI/CD Tools": <HiCog6Tooth className="text-2xl text-gray-600" />,
    "Infrastructure as Code": <SiTerraform className="text-2xl text-purple-600" />,
    "GitAction": <SiGithubactions className="text-2xl text-gray-800 dark:text-white" />,
    "Jenkins": <SiJenkins className="text-2xl text-red-500" />,
    "Nginx": <SiNginx className="text-2xl text-green-600" />,
    "Ansible": <SiAnsible className="text-2xl text-red-600" />,
    "System Design": <FaServer className="text-2xl text-indigo-600" />,
  },
  toolsMonitoring: {
    "Git": <FaGitAlt className="text-2xl text-orange-600" />,
    "Maven": <SiApachemaven className="text-2xl text-red-600" />,
    "Gradle": <SiGradle className="text-2xl text-blue-600" />,
    "Grafana": <SiGrafana className="text-2xl text-orange-500" />,
    "Prometheus": <SiPrometheus className="text-2xl text-orange-600" />,
    "SonarQube": <SiSonarqube className="text-2xl text-blue-500" />,
    "Scripting": <HiCommandLine className="text-2xl text-green-700" />,
    "SSL Certbot Let's Encrypt": <FaShieldAlt className="text-2xl text-green-600" />,
  }
};
