
import {
  FaReact,
  FaNodeJs,
  FaDocker,
  FaAws,
  FaAngular,
  FaJava,
  FaLinux,
} from "react-icons/fa";
import {
  SiSpringboot,
  SiNestjs,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiNginx,
  SiJenkins,
  SiJsonwebtokens,
  SiAuth0,
  SiTypescript,
  SiJavascript,
  SiAnsible,
  SiKubernetes,
  SiRedis,
  SiApachekafka,
  SiNextdotjs,
  SiTailwindcss,
  SiGraphql,
  SiRabbitmq,
  SiElasticsearch,
  SiPrometheus,
  SiGrafana,
  SiGithub,
  SiSonarqube,
} from "react-icons/si";

export const skillIcons = {
  frontend: {
    "React": <FaReact className="text-2xl text-blue-400" />,
    "Angular": <FaAngular className="text-2xl text-red-500" />,
    "Next.js": <SiNextdotjs className="text-2xl text-black dark:text-white" />,
    "Tailwind CSS": <SiTailwindcss className="text-2xl text-blue-400" />,
    "ShadCN UI": <div className="w-8 h-8 rounded-full bg-gray-800 text-white flex items-center justify-center text-xs font-bold">UI</div>,
    "TypeScript": <SiTypescript className="text-2xl text-blue-500" />,
    "JavaScript": <SiJavascript className="text-2xl text-yellow-400" />,
  },
  backendApis: {
    "Java": <FaJava className="text-2xl text-red-600" />,
    "Spring Boot": <SiSpringboot className="text-2xl text-green-600" />,
    "Node.js": <FaNodeJs className="text-2xl text-green-600" />,
    "NestJS": <SiNestjs className="text-2xl text-red-600" />,
    "JWT": <SiJsonwebtokens className="text-2xl text-purple-600" />,
    "OAuth2.0": <SiAuth0 className="text-2xl text-blue-600" />,
    "REST APIs": <div className="w-8 h-8 rounded-full bg-green-500 text-white flex items-center justify-center text-xs font-bold">API</div>,
    "GraphQL": <SiGraphql className="text-2xl text-pink-500" />,
  },
  databases: {
    "MySQL": <SiMysql className="text-2xl text-blue-600" />,
    "MongoDB": <SiMongodb className="text-2xl text-green-600" />,
    "PostgreSQL": <SiPostgresql className="text-2xl text-blue-400" />,
    "Redis": <SiRedis className="text-2xl text-red-500" />,
    "Kafka": <SiApachekafka className="text-2xl text-gray-800" />,
    "RabbitMQ": <SiRabbitmq className="text-2xl text-orange-500" />,
    "Elasticsearch": <SiElasticsearch className="text-2xl text-yellow-500" />,
  },
  devOpsCloud: {
    "Docker": <FaDocker className="text-2xl text-blue-500" />,
    "Nginx": <SiNginx className="text-2xl text-green-600" />,
    "Jenkins": <SiJenkins className="text-2xl text-red-500" />,
    "SSL Certbot Let's Encrypt": <div className="w-8 h-8 rounded-full bg-green-600 text-white flex items-center justify-center text-xs font-bold">SSL</div>,
    "CI/CD": <SiJenkins className="text-2xl text-gray-600" />,
    "Ansible": <SiAnsible className="text-2xl text-red-600" />,
    "Kubernetes": <SiKubernetes className="text-2xl text-blue-500" />,
    "Linux": <FaLinux className="text-2xl text-black dark:text-white" />,
    "AWS": <FaAws className="text-2xl text-orange-400" />,
  },
  qualityMonitoring: {
    "Grafana": <SiGrafana className="text-2xl text-orange-500" />,
    "Prometheus": <SiPrometheus className="text-2xl text-orange-600" />,
    "Git/GitHub": <SiGithub className="text-2xl text-gray-800 dark:text-white" />,
    "SonarQube": <SiSonarqube className="text-2xl text-blue-500" />,
  },
  systemArchitect: {
    "Microservices Architecture": <div className="w-8 h-8 rounded-full bg-purple-500 text-white flex items-center justify-center text-xs font-bold">μS</div>,
    "Distributed Systems": <div className="w-8 h-8 rounded-full bg-blue-500 text-white flex items-center justify-center text-xs font-bold">DS</div>,
    "System Design": <div className="w-8 h-8 rounded-full bg-green-500 text-white flex items-center justify-center text-xs font-bold">SD</div>,
    "Scalable Architecture": <div className="w-8 h-8 rounded-full bg-red-500 text-white flex items-center justify-center text-xs font-bold">SA</div>,
  }
};
