
import {
  FaJava,
  FaPython,
  FaReact,
  FaNodeJs,
  FaDocker,
  FaAws,
  FaAngular,
  FaVuejs,
  FaGitAlt,
  FaFigma,
} from "react-icons/fa";
import {
  SiSpringboot,
  SiExpress,
  SiNestjs,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiNginx,
  SiJenkins,
  SiKeycloak,
  SiJsonwebtokens,
  SiAuth0,
  SiOpenid,
  SiC,
  SiCplusplus,
  SiTypescript,
  SiJavascript,
  SiBitbucket,
  SiAnsible,
  SiKubernetes,
  SiRedis,
  SiApachekafka,
  SiIntellijidea,
  SiPostman,
  SiSwagger,
  SiGithubactions,
} from "react-icons/si";

export const skillIcons = {
  webDev: {
    "C": <SiC className="text-2xl text-blue-600" />,
    "C++": <SiCplusplus className="text-2xl text-blue-700" />,
    "Python": <FaPython className="text-2xl text-yellow-600" />,
    "Java": <FaJava className="text-2xl text-red-600" />,
    "JavaScript": <SiJavascript className="text-2xl text-yellow-400" />,
    "TypeScript": <SiTypescript className="text-2xl text-blue-500" />,
    "ReactJS": <FaReact className="text-2xl text-blue-400" />,
    "Angular": <FaAngular className="text-2xl text-red-500" />,
    "Vue": <FaVuejs className="text-2xl text-green-500" />,
    "NodeJS": <FaNodeJs className="text-2xl text-green-600" />,
    "ExpressJS": <SiExpress className="text-2xl text-gray-600" />,
    "NestJS": <SiNestjs className="text-2xl text-red-600" />,
    "Spring Boot": <SiSpringboot className="text-2xl text-green-600" />,
    "Master Authentication and Authorization": <SiKeycloak className="text-2xl text-blue-600" />,
    "OAuth2.0": <SiAuth0 className="text-2xl text-blue-600" />,
    "Keycloak": <SiKeycloak className="text-2xl text-red-600" />,
    "JWT": <SiJsonwebtokens className="text-2xl text-purple-600" />,
    "OpenID Connect": <SiOpenid className="text-2xl text-orange-600" />,
    "SSO": <SiKeycloak className="text-2xl text-green-600" />,
  },
  databases: {
    "MySQL": <SiMysql className="text-2xl text-blue-600" />,
    "MongoDB": <SiMongodb className="text-2xl text-green-600" />,
    "PostgresQL": <SiPostgresql className="text-2xl text-blue-400" />,
  },
  devOps: {
    "Docker": <FaDocker className="text-2xl text-blue-500" />,
    "Nginx": <SiNginx className="text-2xl text-green-600" />,
    "Jenkins": <SiJenkins className="text-2xl text-red-500" />,
    "Portainer.io": <FaDocker className="text-2xl text-blue-400" />,
    "AWS": <FaAws className="text-2xl text-orange-400" />,
    "Bitbucket": <SiBitbucket className="text-2xl text-blue-600" />,
    "CI/CD": <SiJenkins className="text-2xl text-gray-600" />,
    "Ansible": <SiAnsible className="text-2xl text-red-600" />,
    "Kubernetes": <SiKubernetes className="text-2xl text-blue-500" />,
    "Redis": <SiRedis className="text-2xl text-red-500" />,
    "Kafka": <SiApachekafka className="text-2xl text-gray-800" />,
    "GitHub Actions": <SiGithubactions className="text-2xl text-gray-800" />,
  },
  tools: {
    "VSCode": <div className="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-xs font-bold">VS</div>,
    "IntelliJ IDEA": <SiIntellijidea className="text-2xl text-red-600" />,
    "Git": <FaGitAlt className="text-2xl text-red-500" />,
    "Figma": <FaFigma className="text-2xl text-purple-500" />,
    "Postman": <SiPostman className="text-2xl text-orange-500" />,
    "Swagger API": <SiSwagger className="text-2xl text-green-500" />,
    "Draw.io": <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center text-xs font-bold">D</div>,
  }
};

export const skillLevels = {
  webDev: {
    "Java": 90,
    "JavaScript": 85,
    "TypeScript": 80,
    "ReactJS": 85,
    "Angular": 75,
    "NodeJS": 80,
    "ExpressJS": 85,
    "NestJS": 75,
    "Spring Boot": 90,
    "Master Authentication and Authorization": 85,
    "OAuth2.0": 80
  },
  databases: {
    "MySQL": 85,
    "MongoDB": 80,
    "PostgresQL": 75
  },
  devOps: {
    "Docker": 85,
    "Nginx": 70,
    "Jenkins": 75,
    "AWS": 70,
    "Kubernetes": 65,
    "Redis": 70,
    "Kafka": 60
  },
  tools: {
    "VSCode": 90,
    "IntelliJ IDEA": 85,
    "Git": 90,
    "Figma": 70,
    "Postman": 85,
    "Swagger API": 80
  }
};
