// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdrdqsiujupputofbqpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkcmRxc2l1anVwcHV0b2ZicXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTU5MjgsImV4cCI6MjA2MzYzMTkyOH0.v53i-mSH-FQlbBo9_OO4kLoO3yQJ4XLE4qI25-igy-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);